### ISSUE TITLE
Extrinsic parameter calib problem

### ISSUE THREAD

**Issue by Yangbit666** [neozhaoliang/surround-view-system-introduction#74]
![55014023a9123006d1e042187569757](https://github.com/neozhaoliang/surround-view-system-introduction/assets/126470988/b7fa5aa7-bd35-4ee5-b786-d48691d085c5)
![61b6dd42fbce38b86bb431bee5e2037](https://github.com/neozhaoliang/surround-view-system-introduction/assets/126470988/e5617ef5-4f0f-45ce-ab41-aa9286f070ea)
您好！首先非常感谢您的开源项目
内参标定正常情况下，每一个相机图片过宽。与parameter_setting的哪个参数有关？
doc中说明每个像素代表一厘米，但是对于小车1cm>>1piexel，请问如何换算？

**Comment by rwb1123** [comment]
您好，4个usb摄像头 同时插入四个摄像头，四个都可以检测到，但是不工作，请问如何降低带宽，让四个摄像头同时工作 ？
我用的是jetson nx设备

**Comment by rwb1123** [comment]
@Yangbit666

**Comment by neozhaoliang** [comment]
@Yangbit666 

https://github.com/neozhaoliang/surround-view-system-introduction/blob/master/run_calibrate_camera.py#L12

相机接受一个 resolution 参数。标定以后的 yaml 文件里面会记录这个分辨率。

**Comment by rwb1123** [comment]
您好  请问在测试demo时出现一下情况：
Traceback (most recent call last):
  File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/birdview.py", line 329, in run
    self.make_luminance_balance().stitch_all_parts()
  File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/birdview.py", line 225, in make_luminance_balance
    a1 = utils.mean_luminance_ratio(RII(Rb), FII(Fb), m2)
  File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/utils.py", line 56, in mean_luminance_ratio
    return get_mean_statistisc(grayA, mask) / get_mean_statistisc(grayB, mask)
  File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/utils.py", line 52, in get_mean_statistisc
    return np.sum(gray * mask)
ValueError: operands could not be broadcast together with shapes (500,1600) (550,500)
Aborted (core dumped)
mask和weight图片的尺寸一致
