### ISSUE TITLE
您好 请问在测试demo时出现一下情况： Traceback (most recent call last): File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/birdview.py", line 329, in run self.make_luminance_balance().stitch_all_parts() File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/birdview.py", line 225, in make_luminance_balance a1 = utils.mean_luminance_ratio(RII(Rb), FII(Fb), m2) File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/utils.py", line 56, in mean_luminance_ratio return get_mean_statistisc(grayA, mask) / get_mean_statistisc(grayB, mask) File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/utils.py", line 52, in get_mean_statistisc return np.sum(gray * mask) ValueError: operands could not be broadcast together with shapes (500,1600) (550,500) Aborted (core dumped) mask和weight图片的尺寸一致

### ISSUE THREAD

**Issue by rwb1123** [neozhaoliang/surround-view-system-introduction#75]
您好 请问在测试demo时出现一下情况：
Traceback (most recent call last):
File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/birdview.py", line 329, in run
self.make_luminance_balance().stitch_all_parts()
File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/birdview.py", line 225, in make_luminance_balance
a1 = utils.mean_luminance_ratio(RII(Rb), FII(Fb), m2)
File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/utils.py", line 56, in mean_luminance_ratio
return get_mean_statistisc(grayA, mask) / get_mean_statistisc(grayB, mask)
File "/home/rwb/Downloads/surround-view-system-introduction-master/surround_view/utils.py", line 52, in get_mean_statistisc
return np.sum(gray * mask)
ValueError: operands could not be broadcast together with shapes (500,1600) (550,500)
Aborted (core dumped)
mask和weight图片的尺寸一致

**Comment by GoodLava** [comment]
我也遇到了同样的问题，请问您解决了吗

**Comment by lifei68** [comment]
我也是这个问题，请问怎么解决的
