### ISSUE TITLE
前面都正常运行，但是运行run_get_weight_matrices.py报错

### ISSUE THREAD

**Issue by lifei68** [neozhaoliang/surround-view-system-introduction#81]
Traceback (most recent call last):
  File "/home/lifei/Projects/surround-view-system-introduction-master/run_get_weight_matrices.py", line 36, in <module>
    main()
  File "/home/lifei/Projects/surround-view-system-introduction-master/run_get_weight_matrices.py", line 24, in main
    Gmat, Mmat = birdview.get_weights_and_masks(projected)
  File "/home/lifei/Projects/surround-view-system-introduction-master/surround_view/birdview.py", line 301, in get_weights_and_masks
    G0, M0 = utils.get_weight_mask_matrix(FI(front), LI(left))
  File "/home/lifei/Projects/surround-view-system-introduction-master/surround_view/utils.py", line 123, in get_weight_mask_matrix
    G[y, x] = distToB / (distToA + distToB)
ZeroDivisionError: float division by zero

**Comment by neozhaoliang** [comment]
你那边能画一下 polyA 和 polyB 的图像吗？

**Comment by lifei68** [comment]
谢谢，我解决了，是我参数设置和投影出现了问题

**Comment by FunnyWii** [comment]
> 谢谢，我解决了，是我参数设置和投影出现了问题

请问最后是啥问题啊

**Comment by benwuming** [comment]
我也报了这个错误"/home/lifei/Projects/surround-view-system-introduction-master/surround_view/utils.py", line 123, in get_weight_mask_matrix
G[y, x] = distToB / (distToA + distToB)
ZeroDivisionError: float division by zero 是不是前面做单面俯视图的时候，没有下面那两个角呀？

**Comment by FunnyWii** [comment]
> 我也报了这个错误"/home/lifei/Projects/surround-view-system-introduction-master/surround_view/utils.py", line 123, in get_weight_mask_matrix G[y, x] = distToB / (distToA + distToB) ZeroDivisionError: float division by zero 是不是前面做单面俯视图的时候，没有下面那两个角呀？

检查一下你设置的参数，主要是shift width/height那些
